language: python

python: "2.7"

install:
  - pip install virtualenv
  - pip install coveralls codecov
  - ./setup_venv 

script:
  - ./run_analysis
  - ./run_tests

after_success:
  - coveralls
  - codecov
